### PR TITLE
Marshmallow base

### PR DESCRIPTION
**Pull request by fergy**
Patchset tested.
Please merge

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Thank you for your work. Please next time try to keep a clearer commit history and keep bisectability.

**Comment by fergy** [comment]
Will made clearer next time. Thx

**Comment by nicofossa** [comment]
My SW3 doesn't boot after this merge. It is stuck on "Smartwatch 3" logo: no usb debug, but the screen dim after some time and if I touche the screen/press the button the backlight turns on again

I got a bootable image with `git checkout 3e86825ad0e8852fc53920754757f89bbe0260db`

Hope this can help

**Comment by FlorentRevest** [comment]
Hi nicofossa, thanks a lot for your help.
Any reason why you decided to drop cb6a854006d901d75b27b5180c00524c55f8477a ? I reverted the commits from this PR. This should fix asteroid-launcher on tetra according to your help.

**Pull request merged**
